name: "vitedeployment"
on:
  push:
    branch:
      main
permission:
    contents: read
    pages: write
    token-id: write
jobs:
    github-jobs:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3.5.2 
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.5.2
          with:
              node-version: 18
              cache: npm
        - name: npm install
          uses: npm i
        - name: npm build package
          uses: npm run build
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v3.1.2
          with:
              path: "./dist"
        - name: Deploy GitHub Pages site
          uses: actions/deploy-pages@v2.0.1  
 
      

